spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wya?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug